[versions]
cabe = "4.0.2"
jdk = "0.4.0"
jmh-plugin = "0.7.3"
jreleaser = "1.22.0"
sonar = "7.2.2.6593"
spotbugs-plugin = "6.4.8"
test-logger = "4.0.0"
versions = "0.53.0"

dua3-utility = "21-rc"
jmh = "1.37"
jspecify = "1.0.0"
junit-bom = "6.0.1"
log4j-bom = "2.25.3"
slb4j = "0.1-rc"
spotbugs = "4.9.8"

[libraries]
dua3-utility = { group = "com.dua3.utility", name = "utility" }
dua3-utility-bom = { group = "com.dua3.utility", name = "utility-bom", version.ref = "dua3-utility" }
dua3-utility-db = { group = "com.dua3.utility", name = "utility-db" }
dua3-utility-fx = { group = "com.dua3.utility", name = "utility-fx" }
dua3-utility-fx-controls = { group = "com.dua3.utility", name = "utility-fx-controls" }
dua3-utility-swing = { group = "com.dua3.utility", name = "utility-swing" }
jspecify = { group = "org.jspecify", name = "jspecify", version.ref = "jspecify" }
junit-bom = { group = "org.junit", name = "junit-bom", version.ref = "junit-bom" }
junit-jupiter-api = { group = "org.junit.jupiter", name = "junit-jupiter-api" }
junit-jupiter-engine = { group = "org.junit.jupiter", name = "junit-jupiter-engine" }
junit-platform-launcher = { group = "org.junit.platform", name = "junit-platform-launcher" }
log4j-api = { group = "org.apache.logging.log4j", name = "log4j-api" }
log4j-bom = { group = "org.apache.logging.log4j", name = "log4j-bom", version.ref = "log4j-bom" }
slb4j = { group = "org.slb4j", name = "slb4j", version.ref = "slb4j" }
slb4j-ext = { group = "org.slb4j", name = "slb4j-ext", version.ref = "slb4j" }
slb4j-ext-fx = { group = "org.slb4j", name = "slb4j-ext-fx", version.ref = "slb4j" }

[plugins]
cabe = { id = "com.dua3.cabe", version.ref = "cabe" }
jdk = { id = "com.dua3.gradle.jdkprovider", version.ref = "jdk" }
jmh = { id = "me.champeau.jmh", version.ref = "jmh-plugin" }
jreleaser = { id = "org.jreleaser", version.ref = "jreleaser" }
sonar = { id = "org.sonarqube", version.ref = "sonar" }
spotbugs = { id = "com.github.spotbugs", version.ref = "spotbugs-plugin" }
test-logger = { id = "com.adarshr.test-logger", version.ref = "test-logger" }
versions = { id = "com.github.ben-manes.versions", version.ref = "versions" }
